stages:
  - build
  - package

variables:
  DOCKER_IMAGE: "registry.gitlab.com/your-username/deploy-cv-yolo"

build-mar:
  stage: build
  image: pytorch/torchserve:latest-cpu
  script:
    - mkdir -p serving/torchserve/model-store
    - torch-model-archiver 
        --model-name yolo 
        --version $CI_COMMIT_SHORT_SHA 
        --handler serving/torchserve/yolo_handler.py 
        --extra-files models/weights/best.pt 
        --requirements-file serving/torchserve/requirements.txt 
        --export-path serving/torchserve/model-store 
        --force
  artifacts:
    paths:
      - serving/torchserve/model-store/yolo.mar

build-docker-image:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_TAG -f api-gateway/Dockerfile ./api-gateway
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $DOCKER_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
